name: Build and Deploy Docker Image to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: build-image
        run: |
          IMAGE_TAG="berglund10/my_express_app:${GITHUB_SHA}"
          docker build -t $IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.IMAGE_TAG }}

      - name: Set up Kind and kubectl
        uses: kind-actions/kind-action@v2
        with:
          version: v0.20.0

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/my-express-app my-express-app=${{ env.IMAGE_TAG }} -n profugo
